### ISSUE TITLE
 Getting "MismatchSenderId" with this library

### ISSUE THREAD

**Issue by younes0** [inloop/easygcm#11]
I've been trying everything hours: it looks like that this library causes this error.
The Sender_ID is the right one, this works fines also: 
`am broadcast -a com.google.android.c2dm.intent.RECEIVE -n com.younes0.bnm/eu.inloop.easygcm.GcmBroadcastReceiver --es "type" "foo" `
Did anybody else had the same problem?

**Comment by peterbartos** [comment]
Wasn't this your issue?
http://stackoverflow.com/questions/11307689/when-sending-messages-using-gcm-i-keep-getting-the-response-mismatchsenderid

**Comment by younes0** [comment]
@peterbartos no since that when I stopped using this library, everything was working fine.
I'll close the issue since I can't provide further details.
Thanks.
