### ISSUE TITLE
Registration error handling

### ISSUE THREAD

**Issue by DanielNovak** [inloop/easygcm#19]
We need to provide error handling if the registration fails. Right we don't do anything besides logging the registration result message.

> When registration or unregistration fails, the app should retry the failed operation.
> In the simplest case, if your app attempts to register and GCM is not a fundamental part of the app, the app could simply ignore the error and try to register again the next time it starts. Otherwise, it should retry the previous operation using exponential back-off. In exponential back-off, each time there is a failure, it should wait twice the previous amount of time before trying again.
http://developer.android.com/google/gcm/gcm.html

Currently only restarting the Activity will try retry the GCM registration.

One way would be to add a ```onGcmRegistrationFailed(String errorMessage)``` to the ```GcmListener``` interface. The developer could then implement the retry logic (exponential backoff) and call the initialization again. Although right now this would not work without further modifications because the ```init()``` requires an Activity context (to display the Play Services error dialog).

**Comment by destil** [comment]
Why does the developer need to implement exponential backoff? This doesn't concern his backend, right? I think all developers would want it, I would add it to the library.

**Comment by DanielNovak** [comment]
Yes - the ideal case would be to provide a default back-off implementation in the library. But I am not yet sure how we can terminate these registration retries. We would have to do this on an Activity basis because these retries should stop once you leave the activity or lock the screen. Right now the registration may start independently in an AsyncTask if you receive the MY_PACKAGE_CHANGED broadcast. I am afraid the exponential back-off would keep the app running and eating memory in the background. And there is (I think) no API to check if the whole application is in foreground?

**Comment by destil** [comment]
Why they should stop when you leave the activity? I would do it always in a Service or AsyncTask tied to Application object. Exponential back-off will ensure that the it will not take too much network/battery. It would be a good idea to add some maximum number of retries. But anyway that will happen very rarely.

**Comment by DanielNovak** [comment]
I will try to make a prototype implementation today. This could be either a Handler loop (posting messages with exponentially longer delays) or a Service. I was only afraid that this may keep the app running or consuming battery for a longer time than needed - as a user I would prefer to only try the registration when the app is in the foreground. But adding a maximum number of retries (= maximum running time) could be a good enough safe mechanism.

**Comment by destil** [comment]
I would not worry about that, in 99.9% it will succeed on the first call and developers using this library will be happy that the library does maximum for having your users registered with GCM. Maximum number number of retries can stop some rare exceptions. But you shouldn't keep wakelock all this time, only acquire wakelock when you are actually doing the registration request.
