### ISSUE TITLE
Don't call completeWakefulIntent right after onMessage

### ISSUE THREAD

**Issue by DanielNovak** [inloop/easygcm#2]
The completeWakefulIntent is called right after onMessage. This will work for simple implementations. But there is a high chance that some users will use asynchronous tasks inside onMessage (for example to call HTTP requests). In this case they should be releasing the wake lock themselves after they have completed all the asynchronous work inside onMessage. Otherwise Android might go into sleep during the async work in onMessage.

I propose sending another parameter to onMessage that would allow to release the lock. A simple object like WakeLock with one single method release(). Internally it would store the original Intent and call release on it. (I think it's better to not send the whole intent directly to onMessage - it's not needed and might confuse the developer on what to do with this).

The downside - it will be the responsibility of the developer to call WakeLock.release in onMessage. There has to be some big warning in the documentation (even though it's a bit self-explanatory, because they are getting a "WakeLock" argument into onMessage).

**Comment by adrien-aubel** [comment]
+1!

**Comment by younes0** [comment]
any updates please?

**Comment by martinadamek** [comment]
Are you guys experencing this already? We have added it as a result of code review :-)

**Comment by younes0** [comment]
I didn't make any tests yet to be honest but I do call async tasks in onMessage. Will try to fake a long request and keep you informed.

**Comment by dmalis** [comment]
+1 because, as a good practice and to be on a safe side, one should always complete work before completeWakefulIntent is called
