### ISSUE TITLE
GCM registration is called every time, even if version didn't change

### ISSUE THREAD

**Issue by destil** [inloop/easygcm#22]
GCM registration listens to PACKAGE_REPLACED broadcast. Which is good, but sometimes version doesn't change - typically during development of the app, if you are installing the same version over and over. In that case it's not necessary to repeat registration.

**Comment by DanielNovak** [comment]
+1 - I will try to fix this by storing the last versionCode and comparing.

**Comment by DanielNovak** [comment]
@destil @martinadamek 
I found out that we did not have a way how to specify custom actions if Google Play services are not available. The current version will check if they are not available and show a error dialog if the error code is recoverable, but it will finish the whole activity if the error is not recoverable - which is too strict for most cases.

So this pull request changes the behaviour - by default we always show the error dialog if an error code is returned from ```GooglePlayServicesUtil.isGooglePlayServicesAvailable(activity);```. But you can call ```GcmHelper.setCheckServicesHandler(GcmServicesHandler handler)``` to specify your own behaviour.

And I have fixed the issue if the package is replaced but re-registration is not needed (versionCode has not changed).

Please take a look when you have time, I will merge this in 1-2 days.
