### ISSUE TITLE
Pass Context in sendRegistrationIdToBackend()

### ISSUE THREAD

**Issue by bakua** [inloop/easygcm#31]
Hello, would it be possible to pass Context in mentioned method? It can come handy in some situlations (especially when Application doesn't extend GcmListener).

Thank you

**Comment by DanielNovak** [comment]
I am not absolutely convinced that it's needed. If you are listening inside an Activity or Fragment then you have the Context available. If you have your own class then you could forward Context to that class. And in any case, you can create a static App.getInstance() method that would return the current Application instance (and you can then call App.getInstance().getApplicationContexT()).

**Comment by FrankCharlz** [comment]
Thanks

**Comment by Epholl** [comment]
@bakua have you found a nicer solution to your problem or do you have a use-case, where having the `Context` in `sendRegistrationToBackend()` is the best solution?
