### ISSUE TITLE
BroadcastReceiver trying to return result during a non-ordered broadcast

### ISSUE THREAD

**Issue by kaiyan910** [inloop/easygcm#32]
I don't know it is because of the SDK updated or what I get this error once the app is first launch

BroadcastReceiver trying to return result during a non-ordered broadcast
    java.lang.RuntimeException: BroadcastReceiver trying to return result during a non-ordered broadcast

And it is wired that I get a empty GCM broadcast on the app first launch

Seems the source is this line in the GcmBroadcastReceiver

setResultCode(Activity.RESULT_OK);

would you please have a look on that ? thanks.

**Comment by DanielNovak** [comment]
Probably duplicate of #36 .
