### ISSUE TITLE
Switch lib to use ${applicationId} in manifest once Android bug is fixed

### ISSUE THREAD

**Issue by martinadamek** [inloop/easygcm#34]
Bug was filed on https://code.google.com/p/android/issues/detail?id=156015 and recently got fixed. Probably should appear in dev builds of Android tools soon.

**Comment by martinadamek** [comment]
Bugfix will be release with Studio 1.3.0-beta3

**Comment by destil** [comment]
I tested that if you update to 

com.android.tools.build:gradle:1.3.0-beta3

it works.

**Comment by destil** [comment]
It's not fixed - you should switch to newer version of build tools in the library and remove the ${localApplicationId} hack.

**Comment by DanielNovak** [comment]
Oops :-). Adding @martinadamek to this - can you please fix this?
