### ISSUE TITLE
BroadcastReceiver trying to return result during a non-ordered broadcast.

### ISSUE THREAD

**Issue by mrkcsc** [inloop/easygcm#36]
http://stackoverflow.com/questions/23835970/broadcastreceiver-trying-to-return-result-during-a-non-ordered-broadcast-packa

I think this is the line causing it?  

https://github.com/inloop/easygcm/blob/master/easygcm/src/main/java/eu/inloop/easygcm/GcmBroadcastReceiver.java#L27

**Comment by destil** [comment]
I have the same problem

**Comment by DanielNovak** [comment]
This is actual related to #33 - we have to update the dependencies, it seems that Google once again broke backwards compatibility and they are sending non-ordered broadcasts to GCM in some cases (especially on reinstall). The (deprecated) official document recommends to use setResultCode - but this is not the case anymore. The new docs at https://developers.google.com/cloud-messaging/android/client recommend to use GCMReceiver and GcmListenerService.

I will update easygcm to use the newer version this evening :-). 
Thanks for reporting.
