### ISSUE TITLE
Please implement GcmListener in your Application or use method setGcmListener()

### ISSUE THREAD

**Issue by emack** [inloop/easygcm#37]
This happens when application extends MultiDexApplication

public class App extends MultiDexApplication implements GcmListener{
.....
}

Caused by: java.lang.IllegalStateException: Please implement GcmListener in your Application or use method setGcmListener()
            at eu.inloop.easygcm.GcmHelper.getGcmListener(GcmHelper.java:270)

**Comment by DanielNovak** [comment]
Is this still happening? We could not reproduce this bug.

**Comment by emack** [comment]
I think this was causing the error.

<application
        ...
        android:name="android.support.multidex.MultiDexApplication">
        ...
    </application>

**Comment by peterbartos** [comment]
In the case, you want to use MultiDexApplication, your custom Application class should extend MultiDexApplication and implement GcmListener interface at the same time. Like this:

    public class MyApp extends MultiDexApplication implements GcmListener

and then, in your manifest, you need to refer to this class:

    android:name=".MyApp">
