### ISSUE TITLE
Merging with latest Google GCM sample?

### ISSUE THREAD

**Issue by martinadamek** [inloop/easygcm#40]
Originally this project was based on GCM sample from Google. There is now updated sample at https://developers.google.com/cloud-messaging/android/start with git repo https://github.com/googlesamples/google-services.git

It is using classes like [GcmListenerService](https://developers.google.com/android/reference/com/google/android/gms/gcm/GcmListenerService) that we do not. Would that help us to remove parts of the code and keep everything cleaner?

**Comment by martinadamek** [comment]
Cc @DanielNovak @destil @peterbartos

**Comment by DanielNovak** [comment]
We are actually extending GcmListenerService https://github.com/inloop/easygcm/blob/master/easygcm/src/main/java/eu/inloop/easygcm/EasyGcmListenerService.java

**Comment by martinadamek** [comment]
Oops, wrong search filter in my editor :-)
Does that mean we also looked at current sample and picked some useful stuff (if any)?

**Comment by peterbartos** [comment]
hi @martinadamek, yes we ckecked the current sample :) for example also the new InstanceIDListenerService was included in easygcm. If you find some more useful things, that would be nice!

**Comment by DanielNovak** [comment]
Yes, I think we took almost everything that was useful. The only thing missing is an IntentService instead of an AsyncTask for the server registration task, there is also an issue created for this.

**Comment by martinadamek** [comment]
Cool! Closed and created #41 for AsyncTask -> IntentService migration.
