### ISSUE TITLE
Set maxSdkVersion for GET_ACCOUNTS to 19

### ISSUE THREAD

**Issue by DanielNovak** [inloop/easygcm#43]
Some people are getting errors after uploading to APK like this:
http://stackoverflow.com/questions/31596794/google-play-apk-upload-failure-with-uses-permission-maxsdkversion

We are setting the maxSdkVersion 13 but the lowest possible value is 19, so we just need to change this.

**Comment by destil** [comment]
We have this problem as well. I suggest removing maxSdkVersion alltogether, it causes problems with integrations. And there is no maxSdkVerison in official documentation.

**Comment by destil** [comment]
This permission is not needed anymore in GCM 3.0 according to documentation. Please remove it.

**Comment by DanielNovak** [comment]
Closed in #52.
