### ISSUE TITLE
The package name of permission.C2D_MESSAGE still wrong

### ISSUE THREAD

**Issue by kaiyan910** [inloop/easygcm#45]
Hi I am using latest stable Android Studio with 'com.android.tools.build:gradle:1.3.0' and 'eu.inloop:easygcm:1.5.0@aar'

However when I build the project and check the manifest file the permission row still show 'easygcm.permission.C2D_MESSAGE' instead of '{applicationId}.permission.C2D_MESSAGE' 

As my other project use the same library so once I installed that application I cannot install current application. 

I have checked the Release Log of this library, it should be fixed in latest version, but I still face the problem : (

Can anyone help me ? Thanks so much

**Comment by diogochbittencourt** [comment]
@kaiyan910  I'm facing the same problem. I'm using this library in two different projects and I can't install both in the same device.

**Comment by NorbertSzydlowski** [comment]
+1

**Comment by destil** [comment]
We are having this issue as well.
