### ISSUE TITLE
Update to GCM 8.1.0

### ISSUE THREAD

**Issue by destil** [inloop/easygcm#56]
GCM 8.1.0 introduced a breaking change and all libraries must update. Details:
https://www.reddit.com/r/androiddev/comments/3mehbb/breaking_changes_in_google_play_services_81/

**Comment by Epholl** [comment]
An updated version with GCM 8.1.0 on pull request...

**Comment by DanielNovak** [comment]
https://plus.google.com/u/0/+GoogleDevelopers/posts/HsSNWEQ6H4e

**Comment by DanielNovak** [comment]
Merged #57

**Comment by destil** [comment]
@DanielNovak I think this affects only com.google.android.gms:play-services-analytics:8.1.0
