### ISSUE TITLE
Why is not possible to recall sendRegistrationIdToBackend()

### ISSUE THREAD

**Issue by josefrvaldes** [inloop/easygcm#69]
Hi guys! First of all, thanks for your amazing library. It will save lot of my time.

I was wondering why not to have some way to recall this sendRegistrationIdToBackend method.

I mean.. I know that it's called in the first install of your app once you register by the first time with google, and I think (I'm not really sure, please clarify this) that it's called again once the app is updated.
But what happens if, for example, this first time that you call this method, my server fails?

I know that I can handle it easily, but I think it would be easier to be able to call this method again..

what do you think?

Thanks a lot again!

**Comment by DanielNovak** [comment]
Good question. We will investigate this (with higher priority).

**Comment by Epholl** [comment]
Hello, @josefrvaldes , I suggest you check the methods `boolean EasyGcm.isRegistered(Context context)` and `String EasyGcm.getRegistrationId(Context context)`. Those two should allow you good access to the registrationID as well as information whether the registration already occured (for which the `sendRegistrationIdToBackend` method serves)

**Comment by josefrvaldes** [comment]
Yes, I know that I can use those methods, in fact I'm already using it. But it was just a suggestion.

I will take a look at that GcmListener. It looks interesting. 

Thanks a lot :)

**Comment by Epholl** [comment]
@josefrvaldes How would you suggest the workflow to be improved? The library itself does not have any way to know if the registration process between the application and the backend failed. I can only imagine the `GcmListener` method I mentioned to you in previous post to be invoked manually from within your app if you detect a failed backend registration.

**Comment by josefrvaldes** [comment]
As I still haven't used GcmListener I can't answer you now about it. 

But for example, right now what I'm doing is to have my own method called `registerToBackend()` that is called from inside library's `sendRegistrationIdToBackend().` And after that, if I detect that there was some error during registration, I may call my `registerToBackend()` method again from anywhere.

There is no problem in doing it like this, but that's why I was suggesting that maybe it could be helpful if there was the option to call something like `EasyGcm.resendRegistrationIdToBackend()`

Or maybe you could do `sendRegistrationIdToBackend(String regId)` return true or false depending on the success/error of the transaction and it would trigger something like `onRegistrationOK()` or `onRegistrationError()`.

That last one it's maybe more difficult and needs to be studied. But I think the first suggestion could be fine.

Thanks a lot again for your answers and thanks again for this amazing library! :)

**Comment by Epholl** [comment]
Remaking `sendRegistrationToBackend(String regId)` to return boolean values for the library to know if registration was succesfull or not is not a good idea. The library would then need a mechanism to retry the registration and handle error states, while those can be very specific based on the application architecture. The result of the backend registration - successful or unsuccessful registration to backend is only known to the application and should not be a concern of the library (you would end up having a single lib - easygcm handling 2 responsibilities - GCM + backend registration while having the backend registration actually split to two places).

As for the `EasyGcm.resendRegistrationToBackend()` I think this might be a good idea, although it would need to handle the state when it is called before the actual registration occured (return an error value, special case object or not invoke `sendRegistrationToBackend(regId)` at all?). Currently the behaviour can be simulated using:
`EasyGcm.getGcmListener(context).sendRegistrationIdToBackend(EasyGcm.getRegistrationId());` to which I would also add an if statement with `EasyGcm.isRegistered()` to handle error states.

**Comment by josefrvaldes** [comment]
Yes, I totally understand your first matter.

And about the second matter, if you are currently able to call `EasyGcm.getGcmListener(context).sendRegistrationIdToBackend(EasyGcm.getRegistrationId());` maybe that is all we need and it's not necessary to implement that `EasyGcm.resendRegistrationToBackend()` anymore.

Now the only thing that I suggest is to write that solution in the README file :P

Thanks again!

**Comment by Epholl** [comment]
If you test the solution and it works, please write me here so I can close the issue.
We will add the info to the readme as well as consider adding a `resendRegistrationIdToBackend()` convenience method in the future release :)

Good luck with your app development :)

**Comment by josefrvaldes** [comment]
I just tried this `EasyGcm.getGcmListener(context).sendRegistrationIdToBackend(EasyGcm.getRegistrationId());` and it doesn't work. There is no such method as getGcmListener. There is a setGcmListener but not get.

**Comment by Epholl** [comment]
I see. Sorry, I overlooked the fact, that getGcmListener() is a non-static public method and cannot be accessed. I will ensure a new version with `EasyGcm.resendRegistrationIdToBackend()` convenience method added comes out in a few days.

**Comment by josefrvaldes** [comment]
OK! Thanks a lot!! :)

**Comment by Epholl** [comment]
Added in 1.6.2

**Comment by josefrvaldes** [comment]
Perfect! thanks a lot! :+1: :+1: :+1:
