### ISSUE TITLE
Does the token expire? 

### ISSUE THREAD

**Issue by Rainer-Lang** [inloop/easygcm#71]
If yes - how to handle this with the lib?

**Comment by Epholl** [comment]
If you mean `EasyInstanceIDListenerService.onTokenRefresh()`, the method is called in case of security issues and the lib will automatically perform a new registration. The result will be propagated to your application the same way as during the first gcm registration.

**Comment by Rainer-Lang** [comment]
@Epholl Yes - I think this is what I'm looking for. :-)
Thanks.
